[credentials]

#Login names + profile + hashed password
[credentials.usernames]
alice = { name = "Alice Smith", email = "alice@example.com", password = "alice" }
bob   = { name = "Bob Johnson", email = "bob@example.com", password = "bob" }

#Assign each user a role (user or expert)
[credentials.roles]
alice = "user"
bob   = "expert"

# (Optional) cookie settings  
# cookie_name = "mindease_auth"  
# key         = "any_random_string"  
# expiry_days = 1
